import { useEffect, useRef, useState } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import "animate.css";
import FadeIn from "@/components/FadeIn";
import FadeOut from "@/components/FadeOut";

export const FADE_IN_TIME = 5000;
export const FADE_OUT_TIME = 7500;
type InputResponse = {
  input: string;
  response: string;
};

export default function Home() {
  const [currentText, setCurrentText] = useState<string>(
    "Hello, my name is Tom Riddle."
  );
  const [showText, setShowText] = useState<boolean>(true);
  const [showInput, setShowInput] = useState<boolean>(false);
  const [inputText, setInputText] = useState<string>("Type something here...");
  const [submittedInputs, setSubmittedInputs] = useState<InputResponse[]>([]);
  const [loading, setLoading] = useState<boolean>(false);
  const inputDiv = useRef<HTMLInputElement>(null);
  const submit = () => {
    setLoading(true);
    fetch("/api/ask-tom", {
      method: "POST",
      body: JSON.stringify({
        input: inputText,
        submittedInputs,
      }),
    }).then((res) => {
      res.json().then((data) => {
        setCurrentText(data.response);
        setSubmittedInputs([
          ...submittedInputs,
          { input: data.input, response: data.response },
        ]);
        console.log("current text", currentText);
        console.log("data", data.response);
        setShowText(true);
        setShowInput(false);
        setLoading(false);
      });
    });
    setInputText("go again?");
  };
  useEffect(() => {
    setTimeout(() => {
      setShowText(false);
    }, FADE_IN_TIME);
    setTimeout(() => {
      setShowInput(true);
    }, FADE_IN_TIME + FADE_OUT_TIME);
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Italianno&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Patrick+Hand&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main className={styles.main}>
        {showText ? (
          <FadeIn>
            <h1
              style={{
                fontFamily: "Italianno, cursive",
                fontSize: "120px",
              }}
            >
              {currentText}
            </h1>
          </FadeIn>
        ) : (
          <FadeOut>
            <h1
              style={{
                fontFamily: "Italianno, cursive",
                fontSize: "120px",
              }}
            >
              {currentText}
            </h1>
          </FadeOut>
        )}
        {showInput && !loading && (
          <>
            <FadeIn>
              <input
                type="text"
                style={{
                  outline: "0px solid transparent",
                  fontFamily: "Patrick Hand",
                  fontSize: "100px",
                  width: "100%",
                  height: "100%",
                  flexBasis: "100%",
                  textAlign: "center",
                  border: "none",
                  background: "none",
                }}
                spellCheck={false}
                ref={inputDiv}
                onFocus={() => {
                  if (
                    inputText === "Type something here..." ||
                    inputText === "go again?"
                  )
                    setInputText("");
                }}
                color={
                  inputText === "Type something here..." ? "gray" : "white"
                }
                value={inputText}
                onChange={(e) => {
                  e.preventDefault();
                  setInputText(e.target.value);
                }}
                onKeyDown={(e) => {
                  console.log("hello on key down");
                  if (e.key === "Enter") {
                    submit();
                  }
                }}
              ></input>
            </FadeIn>

            <button
              style={{
                outline: "none",
                boxShadow: "none",
                borderRadius: "0px",
                marginTop: "50px",
                width: "200px",
                height: "50px",
                background: "none",
                borderStyle: "solid",
                borderColor: "white",
                fontSize: "30px",
                fontFamily: "Patrick Hand",
              }}
              onClick={(e) => {
                submit();
              }}
            >
              Go!
            </button>
          </>
        )}
      </main>
    </>
  );
}
